// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/diary/diary.proto

package diary

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiaryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiaryRequest) Reset()         { *m = DiaryRequest{} }
func (m *DiaryRequest) String() string { return proto.CompactTextString(m) }
func (*DiaryRequest) ProtoMessage()    {}
func (*DiaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{0}
}

func (m *DiaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiaryRequest.Unmarshal(m, b)
}
func (m *DiaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiaryRequest.Marshal(b, m, deterministic)
}
func (m *DiaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiaryRequest.Merge(m, src)
}
func (m *DiaryRequest) XXX_Size() int {
	return xxx_messageInfo_DiaryRequest.Size(m)
}
func (m *DiaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiaryRequest proto.InternalMessageInfo

func (m *DiaryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiaryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DiaryRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DiaryResource struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Previous             string               `protobuf:"bytes,6,opt,name=previous,proto3" json:"previous,omitempty"`
	Next                 string               `protobuf:"bytes,7,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiaryResource) Reset()         { *m = DiaryResource{} }
func (m *DiaryResource) String() string { return proto.CompactTextString(m) }
func (*DiaryResource) ProtoMessage()    {}
func (*DiaryResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{1}
}

func (m *DiaryResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiaryResource.Unmarshal(m, b)
}
func (m *DiaryResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiaryResource.Marshal(b, m, deterministic)
}
func (m *DiaryResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiaryResource.Merge(m, src)
}
func (m *DiaryResource) XXX_Size() int {
	return xxx_messageInfo_DiaryResource.Size(m)
}
func (m *DiaryResource) XXX_DiscardUnknown() {
	xxx_messageInfo_DiaryResource.DiscardUnknown(m)
}

var xxx_messageInfo_DiaryResource proto.InternalMessageInfo

func (m *DiaryResource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiaryResource) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DiaryResource) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *DiaryResource) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DiaryResource) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *DiaryResource) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *DiaryResource) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type DiaryResources struct {
	Diaries              []*DiaryResource `protobuf:"bytes,1,rep,name=diaries,proto3" json:"diaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DiaryResources) Reset()         { *m = DiaryResources{} }
func (m *DiaryResources) String() string { return proto.CompactTextString(m) }
func (*DiaryResources) ProtoMessage()    {}
func (*DiaryResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{2}
}

func (m *DiaryResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiaryResources.Unmarshal(m, b)
}
func (m *DiaryResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiaryResources.Marshal(b, m, deterministic)
}
func (m *DiaryResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiaryResources.Merge(m, src)
}
func (m *DiaryResources) XXX_Size() int {
	return xxx_messageInfo_DiaryResources.Size(m)
}
func (m *DiaryResources) XXX_DiscardUnknown() {
	xxx_messageInfo_DiaryResources.DiscardUnknown(m)
}

var xxx_messageInfo_DiaryResources proto.InternalMessageInfo

func (m *DiaryResources) GetDiaries() []*DiaryResource {
	if m != nil {
		return m.Diaries
	}
	return nil
}

type DiaryId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiaryId) Reset()         { *m = DiaryId{} }
func (m *DiaryId) String() string { return proto.CompactTextString(m) }
func (*DiaryId) ProtoMessage()    {}
func (*DiaryId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{3}
}

func (m *DiaryId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiaryId.Unmarshal(m, b)
}
func (m *DiaryId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiaryId.Marshal(b, m, deterministic)
}
func (m *DiaryId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiaryId.Merge(m, src)
}
func (m *DiaryId) XXX_Size() int {
	return xxx_messageInfo_DiaryId.Size(m)
}
func (m *DiaryId) XXX_DiscardUnknown() {
	xxx_messageInfo_DiaryId.DiscardUnknown(m)
}

var xxx_messageInfo_DiaryId proto.InternalMessageInfo

func (m *DiaryId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DiarySnapshot struct {
	Snapshot             []byte   `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiarySnapshot) Reset()         { *m = DiarySnapshot{} }
func (m *DiarySnapshot) String() string { return proto.CompactTextString(m) }
func (*DiarySnapshot) ProtoMessage()    {}
func (*DiarySnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{4}
}

func (m *DiarySnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiarySnapshot.Unmarshal(m, b)
}
func (m *DiarySnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiarySnapshot.Marshal(b, m, deterministic)
}
func (m *DiarySnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiarySnapshot.Merge(m, src)
}
func (m *DiarySnapshot) XXX_Size() int {
	return xxx_messageInfo_DiarySnapshot.Size(m)
}
func (m *DiarySnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_DiarySnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_DiarySnapshot proto.InternalMessageInfo

func (m *DiarySnapshot) GetSnapshot() []byte {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type DiarySnapshotId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiarySnapshotId) Reset()         { *m = DiarySnapshotId{} }
func (m *DiarySnapshotId) String() string { return proto.CompactTextString(m) }
func (*DiarySnapshotId) ProtoMessage()    {}
func (*DiarySnapshotId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e382ecc22f169977, []int{5}
}

func (m *DiarySnapshotId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiarySnapshotId.Unmarshal(m, b)
}
func (m *DiarySnapshotId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiarySnapshotId.Marshal(b, m, deterministic)
}
func (m *DiarySnapshotId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiarySnapshotId.Merge(m, src)
}
func (m *DiarySnapshotId) XXX_Size() int {
	return xxx_messageInfo_DiarySnapshotId.Size(m)
}
func (m *DiarySnapshotId) XXX_DiscardUnknown() {
	xxx_messageInfo_DiarySnapshotId.DiscardUnknown(m)
}

var xxx_messageInfo_DiarySnapshotId proto.InternalMessageInfo

func (m *DiarySnapshotId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DiaryRequest)(nil), "DiaryRequest")
	proto.RegisterType((*DiaryResource)(nil), "DiaryResource")
	proto.RegisterType((*DiaryResources)(nil), "DiaryResources")
	proto.RegisterType((*DiaryId)(nil), "DiaryId")
	proto.RegisterType((*DiarySnapshot)(nil), "DiarySnapshot")
	proto.RegisterType((*DiarySnapshotId)(nil), "DiarySnapshotId")
}

func init() { proto.RegisterFile("app/diary/diary.proto", fileDescriptor_e382ecc22f169977) }

var fileDescriptor_e382ecc22f169977 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0xf3, 0xd5, 0x36, 0x3b, 0xbb, 0xdb, 0x45, 0x23, 0x40, 0x21, 0x1c, 0xe8, 0xfa, 0x80,
	0x22, 0x21, 0x39, 0x4b, 0xe1, 0x80, 0xb8, 0x21, 0x2d, 0x02, 0x24, 0x84, 0x56, 0x29, 0x3c, 0x40,
	0xda, 0x98, 0x62, 0xa9, 0xad, 0x4d, 0xec, 0x14, 0x78, 0x68, 0x2e, 0x3c, 0x01, 0xb2, 0x93, 0x14,
	0x92, 0xaa, 0x05, 0xed, 0xc5, 0x9a, 0x8f, 0xdf, 0x8c, 0xff, 0x33, 0x36, 0xdc, 0xcb, 0xa5, 0x4c,
	0x0b, 0x9e, 0x97, 0x3f, 0xea, 0x93, 0xca, 0x52, 0x68, 0x11, 0x3f, 0x5c, 0x0a, 0xb1, 0x5c, 0xb1,
	0xd4, 0x7a, 0xf3, 0xea, 0x73, 0xca, 0xd6, 0x52, 0xb7, 0xc9, 0x47, 0xfd, 0xa4, 0xe6, 0x6b, 0xa6,
	0x74, 0xbe, 0x96, 0x35, 0x40, 0xde, 0xc2, 0xd9, 0xb5, 0x69, 0x96, 0xb1, 0xaf, 0x15, 0x53, 0x1a,
	0xc7, 0xe0, 0xf1, 0x22, 0x72, 0x27, 0x6e, 0x72, 0x92, 0x79, 0xbc, 0xc0, 0xbb, 0x30, 0xd0, 0x5c,
	0xaf, 0x58, 0xe4, 0xd9, 0x50, 0xed, 0x20, 0x42, 0xa0, 0xd9, 0x77, 0x1d, 0xf9, 0x36, 0x68, 0x6d,
	0xf2, 0xd3, 0x85, 0xf3, 0xa6, 0x95, 0x12, 0x55, 0xb9, 0x60, 0xb7, 0xef, 0x85, 0x2f, 0xe0, 0x64,
	0x51, 0xb2, 0x5c, 0xb3, 0xe2, 0x95, 0x8e, 0x82, 0x89, 0x9b, 0x9c, 0x4e, 0x63, 0x5a, 0x8f, 0x42,
	0xdb, 0x51, 0xe8, 0xc7, 0x76, 0x94, 0xec, 0x0f, 0x6c, 0x2a, 0x2b, 0x59, 0x34, 0x95, 0x83, 0x7f,
	0x57, 0xee, 0x60, 0x8c, 0x21, 0x94, 0x25, 0xdb, 0x72, 0x51, 0xa9, 0x68, 0x68, 0xb5, 0xec, 0x7c,
	0xa3, 0x71, 0x63, 0x34, 0x8e, 0x6a, 0x8d, 0xc6, 0x26, 0x2f, 0x61, 0xdc, 0x19, 0x57, 0x61, 0x02,
	0x23, 0xf3, 0x30, 0x9c, 0xa9, 0xc8, 0x9d, 0xf8, 0xc9, 0xe9, 0x74, 0x4c, 0x3b, 0x44, 0xd6, 0xa6,
	0xc9, 0x03, 0x18, 0xd9, 0xcc, 0xbb, 0xa2, 0xbf, 0x24, 0xf2, 0xa4, 0xd9, 0xe2, 0x6c, 0x93, 0x4b,
	0xf5, 0x45, 0x58, 0x5d, 0xaa, 0xb1, 0x2d, 0x76, 0x96, 0xed, 0x7c, 0x72, 0x09, 0x17, 0x1d, 0x78,
	0xbf, 0xdf, 0xf4, 0x97, 0x07, 0x03, 0xcb, 0xe0, 0x25, 0xf8, 0x6f, 0x98, 0xc6, 0x90, 0x36, 0x57,
	0xc7, 0x3d, 0x79, 0xc4, 0xc1, 0xa7, 0x10, 0xbc, 0xe7, 0x4a, 0xe3, 0xfd, 0xbd, 0x95, 0xbd, 0x36,
	0x9f, 0x2a, 0xbe, 0xe8, 0x56, 0x28, 0xe2, 0x20, 0x81, 0xe0, 0x83, 0x79, 0xb2, 0x63, 0x6d, 0x1f,
	0x43, 0x78, 0xd3, 0xae, 0xf2, 0x18, 0x97, 0x42, 0x30, 0xcb, 0xb7, 0x0c, 0xcf, 0xe9, 0xdf, 0x7f,
	0x32, 0x3e, 0xa0, 0x86, 0x38, 0x48, 0xc1, 0xbf, 0xa9, 0xf4, 0xff, 0xf3, 0x57, 0x10, 0x5e, 0x8b,
	0x6f, 0x9b, 0x95, 0xc8, 0x0b, 0xbc, 0x43, 0x7b, 0xab, 0x6b, 0x05, 0xb5, 0x11, 0xe2, 0x5c, 0xb9,
	0xf8, 0x1c, 0x86, 0x9f, 0xa4, 0xe5, 0x7b, 0xd9, 0xc3, 0xb7, 0x24, 0xee, 0x7c, 0x68, 0x63, 0xcf,
	0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xea, 0xbc, 0x77, 0xa6, 0xb3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiaryClient is the client API for Diary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiaryClient interface {
	Get(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DiaryResources, error)
	Next(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error)
	Previous(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error)
	Save(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Put(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Download(ctx context.Context, in *DiarySnapshotId, opts ...grpc.CallOption) (Diary_DownloadClient, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (Diary_UploadClient, error)
}

type diaryClient struct {
	cc *grpc.ClientConn
}

func NewDiaryClient(cc *grpc.ClientConn) DiaryClient {
	return &diaryClient{cc}
}

func (c *diaryClient) Get(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error) {
	out := new(DiaryResource)
	err := c.cc.Invoke(ctx, "/Diary/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DiaryResources, error) {
	out := new(DiaryResources)
	err := c.cc.Invoke(ctx, "/Diary/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) Next(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error) {
	out := new(DiaryResource)
	err := c.cc.Invoke(ctx, "/Diary/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) Previous(ctx context.Context, in *DiaryId, opts ...grpc.CallOption) (*DiaryResource, error) {
	out := new(DiaryResource)
	err := c.cc.Invoke(ctx, "/Diary/Previous", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) Save(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Diary/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) Put(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Diary/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) Download(ctx context.Context, in *DiarySnapshotId, opts ...grpc.CallOption) (Diary_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Diary_serviceDesc.Streams[0], "/Diary/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &diaryDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Diary_DownloadClient interface {
	Recv() (*DiarySnapshot, error)
	grpc.ClientStream
}

type diaryDownloadClient struct {
	grpc.ClientStream
}

func (x *diaryDownloadClient) Recv() (*DiarySnapshot, error) {
	m := new(DiarySnapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *diaryClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Diary_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Diary_serviceDesc.Streams[1], "/Diary/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &diaryUploadClient{stream}
	return x, nil
}

type Diary_UploadClient interface {
	Send(*DiarySnapshot) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type diaryUploadClient struct {
	grpc.ClientStream
}

func (x *diaryUploadClient) Send(m *DiarySnapshot) error {
	return x.ClientStream.SendMsg(m)
}

func (x *diaryUploadClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiaryServer is the server API for Diary service.
type DiaryServer interface {
	Get(context.Context, *DiaryId) (*DiaryResource, error)
	List(context.Context, *empty.Empty) (*DiaryResources, error)
	Next(context.Context, *DiaryId) (*DiaryResource, error)
	Previous(context.Context, *DiaryId) (*DiaryResource, error)
	Save(context.Context, *DiaryRequest) (*empty.Empty, error)
	Put(context.Context, *DiaryRequest) (*empty.Empty, error)
	Download(*DiarySnapshotId, Diary_DownloadServer) error
	Upload(Diary_UploadServer) error
}

// UnimplementedDiaryServer can be embedded to have forward compatible implementations.
type UnimplementedDiaryServer struct {
}

func (*UnimplementedDiaryServer) Get(ctx context.Context, req *DiaryId) (*DiaryResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDiaryServer) List(ctx context.Context, req *empty.Empty) (*DiaryResources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedDiaryServer) Next(ctx context.Context, req *DiaryId) (*DiaryResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (*UnimplementedDiaryServer) Previous(ctx context.Context, req *DiaryId) (*DiaryResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Previous not implemented")
}
func (*UnimplementedDiaryServer) Save(ctx context.Context, req *DiaryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedDiaryServer) Put(ctx context.Context, req *DiaryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedDiaryServer) Download(req *DiarySnapshotId, srv Diary_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedDiaryServer) Upload(srv Diary_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterDiaryServer(s *grpc.Server, srv DiaryServer) {
	s.RegisterService(&_Diary_serviceDesc, srv)
}

func _Diary_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).Get(ctx, req.(*DiaryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).Next(ctx, req.(*DiaryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_Previous_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).Previous(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/Previous",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).Previous(ctx, req.(*DiaryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).Save(ctx, req.(*DiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diary/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).Put(ctx, req.(*DiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiarySnapshotId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiaryServer).Download(m, &diaryDownloadServer{stream})
}

type Diary_DownloadServer interface {
	Send(*DiarySnapshot) error
	grpc.ServerStream
}

type diaryDownloadServer struct {
	grpc.ServerStream
}

func (x *diaryDownloadServer) Send(m *DiarySnapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _Diary_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DiaryServer).Upload(&diaryUploadServer{stream})
}

type Diary_UploadServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*DiarySnapshot, error)
	grpc.ServerStream
}

type diaryUploadServer struct {
	grpc.ServerStream
}

func (x *diaryUploadServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *diaryUploadServer) Recv() (*DiarySnapshot, error) {
	m := new(DiarySnapshot)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Diary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Diary",
	HandlerType: (*DiaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Diary_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Diary_List_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _Diary_Next_Handler,
		},
		{
			MethodName: "Previous",
			Handler:    _Diary_Previous_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Diary_Save_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Diary_Put_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _Diary_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _Diary_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "app/diary/diary.proto",
}
